### ISSUE TITLE
Визуальное оформление стен в лабиринте

### ISSUE THREAD

**Issue by latinrice** [pdshka/Bitter-Sweet#32]
Отсутствие верхней части стены там, где она должна быть: 

![изображение](https://user-images.githubusercontent.com/92548405/231844651-e4e7d86b-e3ea-4730-8aa9-b2839e1d43cd.png)  

![изображение](https://user-images.githubusercontent.com/92548405/231845561-0bc07bfb-dbef-47b8-9f18-39f2352d6a0a.png)

**Comment by Luizett** [comment]
Решено
