### ISSUE TITLE
Как анимировать?

### ISSUE THREAD

**Issue by Luizett** [pdshka/Bitter-Sweet#37]
Небольшой пошаговый гайд

**Comment by Luizett** [comment]
1. Для того, чтобы добавить анимацию к объекту к нему нужно добавить компонент Animator. Кроме того, всегда хорошо также добавлять компонент Sprite renderer, для того чтобы явно видеть объект вне режима игры. 
![image](https://user-images.githubusercontent.com/92753486/233462341-31ff1d0f-f5f7-4ed5-bd33-fede888efdb3.png)

2. Поговорим про изображения для анимации. Они должны быть настроены правильно, так например если на изображении много кадров подряд оно должно иметь следующие настройки и вид: 
![image](https://user-images.githubusercontent.com/92753486/233463316-29f04487-745c-4cc8-9c91-9a48688632bd.png)
![image](https://user-images.githubusercontent.com/92753486/233463436-5db0bc86-bf57-4aea-a396-95fb3a1fe9bb.png)
_Если придётся изменять настройки, не забудьте нажать кнопочку apply для применения изменений. Если при раскрытии картинки по стрелочке в окне проекта она не распадается на маленькие картинки кадры - это значит что её нужно порезать в Sprite Editor(гуглите, или пишите мне в таких случаях). Замечу также, что настройку Sprite mode - multiple нужно ставить только если на изображении много кадров_

3. Когда изображения подготовлены, создаём в папке проекта Animator controller. В нём уже есть какие-то стандартные состояния. Создаём в папке проекта объект Animation и перетаскиваем его в окно, отрывшееся после создания контроллера. У меня оно сразу привязалось к состоянию, но если так е происходит, то правая кнопка мыши по состоянию -> Make transition и перетягиваем стрелочку к анимации. Теперь анимация будет запускаться, когда объект входит в это состояние. Всё выглядит примерно так: 
![image](https://user-images.githubusercontent.com/92753486/233465870-19a0c38a-1507-4312-81cb-10cf316d84d1.png)
_Очевидно, стоит давать понятные логичные названия всему, что создаёте_
4. Если нужно чтоб анимация зацикливалась (а так нужно почти всегда), нажимаем на неё **в папке проекта** и ставим галочку Loop Time
5. Возвращаемся к объекту и переносим созданный контроллер анимации в поле аниматора
6. Кликаем 2 раза **на объект анимации в папке проекта**, переходим на сцену и нажимаем на объект, который анимируем(или в инспекторе выбираем). Окошко анимации сразу становится более отзывчивым, все кнопки загораются.
7. Открываем папку со спрайтами и начинаем по очереди переносить каждый кадр в окошко анимации. Рекомендую ставить кадры на расстоянии 15 миллисекунд друг от друга, так получается средне по скорости. Пожалуйста, делайте это внимательно и осторожно, соблюдайте последовательность кадров и устанавливайте их точно каждые 15 миллисекунд, потому что потом глаза режет. 
Кроме того **выполните одно из условий**: или продублируйте последний кадр так, чтоб он находился через 14 мс после последнего(т.е. в конце будет 2 одинаковых кадра но последний не через 15 секунд, а через 14), или  найдите место где вы ставили галочку на луп тайм и напишите там во времени 15(я не уверена насколько правильно это будет работать, потому что пользуюсь способом 1)
8. Запускаем игру и проверяем анимацию, подождите пока она проиграется полностью. чтоб удостовериться, что точно всё хорошо. Также можно смотреть на проигрывание вашей расчудесной анимации если нажать в окне аниматора на плей - тогда она начнёт проигрываться прямо на сцене, очень удобно

**Comment by latinrice** [comment]
Классный гайд, без лишней воды, всё понятно
