### ISSUE TITLE
Основное

### ISSUE THREAD

**Issue by Luizett** [pdshka/Bitter-Sweet#4]
Здесь будут задачи, касающиеся более-менее глобальных изменений игры

**Comment by Luizett** [comment]
Первые этапы
- [ ] создать объект персонажа и **реализовать передвижение**
- [ ] сцену для 1 локации
- [ ] место/объект телепорт из кафе на локацию 1

**Comment by latinrice** [comment]
- [ ] создать объект телепорта(?), в котором можно настроить сцену, на которую он будет перемещать
- [ ] шаблон системы диалогов (триггеры для разговора с самим собой)
